[package]
name = "data_feeder"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = { version = "0.4", features = ["serde"] }
postgres-types = { version = "0.2", features = ["derive", "with-chrono-0_4"] }
csv = "1.3"
futures = "0.3"
heed = "0.20"
kameo = "0.14"
reqwest = { version = "0.11", features = ["blocking", "json"] }
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = "0.6"
tempfile = "3.10.1"
rayon = "1.10"
tokio-tungstenite = { version = "0.20", features = ["native-tls"] }
futures-util = "0.3"
serde_json = "1.0"
tokio-postgres = "0.7"
deadpool-postgres = "0.10"
toml = "0.8"
